import dynamic from "next/dynamic";
import Head from "next/head";
import {setSidebarDisplay} from "@Dto/states";
const ResetpasswordComp = dynamic(() => import("@Component/ResetpasswordComp"));
const Resetpassword = ({ slug }) => {
    setSidebarDisplay(true)
    return <>
        <Head>
            {/* <title>IGX2 | News {title}</title> */}
            <meta name="description" content="Generated by Golf live page" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
           <ResetpasswordComp slug={slug}/>
        </main>
    </>
}
export async function getServerSideProps({ query }) {
    let { slug } = query

    return {
        props: {
            slug
        },
    }
}

export default Resetpassword
