import dynamic from "next/dynamic";
import Head from "next/head";
const TableNodata = dynamic(() => import("@Component/commons/TableNodata"));
const Favorite = dynamic(() => import("@Component/Favorites"));
import useCurrentTouraments from "store/useCurrentTouraments";
import useFavorite from "store/useFavorite";
import {setSidebarDisplay} from "@Dto/states";

const Favorites = ({ }) => {
    const { currentTournames } = useCurrentTouraments()
    const { favorites, totalFav, setFavorites } = useFavorite();
    const onChangeLocalStorage = (slugName, items, infors) => {
        let newfavorites = {...favorites}
        newfavorites[slugName] = { items, infors };
        setFavorites(newfavorites)
    }
    setSidebarDisplay(true)
    return <>
        <Head>
            <title>IGX2 | Favorites</title>
            <meta name="description" content="Generated by Golf live page" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            {totalFav > 0 ?
                <Favorite currentTournames={currentTournames} favorites={favorites} onChangeLocalStorage={onChangeLocalStorage}/> : <TableNodata text="No Favorites"/>}
        </main>

    </>
}
export default Favorites
