import Head from "next/head";
import Faq from "@Data/faq"
import {setSidebarDisplay} from "@Dto/states";
import {BigContainer, Container, ContainerLDP, WrapperLDP} from "@Styles/container";
import dynamic from "next/dynamic";
import { Get } from "@Dto/Api";
import {findAllFaq} from "../../graphQL/findAllFaq";
const FAQComp = dynamic(() => import("@Component/Faq"));


export default function FAQ({data}){
    setSidebarDisplay(false)
    return <>
        <Head>
            <title>Golf Live FAQ</title>
            <meta name="description" content="Generated by Golf live page" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <BigContainer className={'none-sidebar'}>
                <WrapperLDP>
                    <ContainerLDP>
                        <FAQComp data={data}/>
                    </ContainerLDP>
                </WrapperLDP>
            </BigContainer>
        </main>
    </>
}
export async function getServerSideProps({ req, res }) {
    const { data } = await Get({query: findAllFaq()})
    
    return {
        props: {
            data: data.findAllFaq
        },
    };
}
