import {Get} from "@Dto/Api";
import {findAboutUs} from "../../graphQL/findAboutUs";
import Head from "next/head";
import {Masthead} from "@Component/About/Masthead";
import {setSidebarDisplay} from "@Dto/states";
import {BigContainer, Container, ContainerLDP, WrapperLDP} from "@Styles/container";
import Feature from "@Component/About/Feature";


export default function About({data}){
    setSidebarDisplay(false)
    return <>
        <Head>
            <title>Golf Live About</title>
            <meta name="description" content="Generated by Golf live page" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <BigContainer className={'hidden-ball none-sidebar'}>
                <WrapperLDP>
                    <ContainerLDP>
                        <Masthead data={data}/>
                        <Feature data={data}/>
                    </ContainerLDP>
                </WrapperLDP>
            </BigContainer>
        </main>
    </>
}
export async function getServerSideProps({ req, res }) {
    const { data } = await Get({query: findAboutUs()})
    return {
        props: {
            data: data.findAboutUs
        },
    };
}
