import dynamic from "next/dynamic";
import Head from "next/head";
import { getNewsData } from "store/useApi";
import { useEffect, useMemo, useState } from "react";
import useTranslation from 'next-translate/useTranslation'
import {setSidebarDisplay} from "@Dto/states";
import { Get } from "@Dto/Api";
import { findAllNews } from "graphQL/news";
const Masthead = dynamic(() => import("@Component/global/Masthead"))
const PlayerComparison = dynamic(() => import("@Component/PlayerComparison"))
const ListPosts = dynamic(() => import("@Component/global/ListPosts"))
const BackToTopButton = dynamic(() => import("@Component/global/BackToTop"))
const page = 1
const limit = 24
export default function Home({ news, global }) {
  const { t } = useTranslation();
  setSidebarDisplay(true);

  return <>
    <Head>
      <title>Golf live page</title>
      <meta name="description" content="Generated by Golf live page" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Masthead posts={news}/>
      {/* <ListPosts category="announcements" classPagination="swiper-pagination-announcements"/> */}
      <ListPosts classPagination="swiper-pagination-news"/>
      <PlayerComparison data={global.comparison} trans={t} />
      <BackToTopButton />
    </main>
  </>
}

export async function getServerSideProps({ query }) {
  const { data } = await Get({ query: findAllNews({ page, limit, category: "news" }) });

  return {
    props: {
      news: data?.findAllNewsInCMS?.docs
    },
  }
}

