import dynamic from "next/dynamic";
import Head from "next/head";
const DynamicMasthead = dynamic(() => import("@Component/Promotions/Masthead"));
const DynamicPromotions = dynamic(() => import("@Component/Promotions/Promotions"));
import { Get } from "@Dto/Api";
import {findAllPromotion} from "../../graphQL/findAllPromotion";
import {setSidebarDisplay} from "@Dto/states";
import {BigContainer, ContainerLDP, WrapperLDP} from "@Styles/container";

const Promotion = ({ data }) => {
    setSidebarDisplay(false)

    return <>
        <Head>
            <title>IGX2 | Favorites</title>
            <meta name="description" content="Generated by Golf live page" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <BigContainer className={'hidden-ball none-sidebar'}>
                <WrapperLDP style={{paddingTop:0}}>
                    <DynamicMasthead pros={data}/>
                    <ContainerLDP>
                        <DynamicPromotions promotionList={data}/>
                    </ContainerLDP>
                </WrapperLDP>
            </BigContainer>
        </main>
    </>
}
export async function getServerSideProps() {
    const { data } = await Get({query: findAllPromotion(1, 12)})
    return {
        props: {
            data: data.findAllPromotion.docs
        },
    }
}

export default Promotion
